// <auto-generated />
namespace Web2ProjBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class web2projMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(web2projMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202106111135584_web2projMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
